---
title: "Intro R Workshop Outline"
authors: Emily Read and Luke Winslow
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_vignette:
    toc: true
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Intro R Workshop Outline}
  \usepackage[utf8]{inputenc}
---
This workshop is designed to provide training and tools to perform common data analysis workflow steps: 

get -> clean -> explore -> analyze -> visualize -> repeat

The workshop and materials are hands-on and include examples and exercises. After completing the workshop, you won't be an R expert, but should have the foundation for getting started on your own data analysis work in R and will know where and how to get help. 

We have borrowed from many sources for this material, most signficantly from Jeffery W. Hollister's IntroR course. Thank you, Jeff, for openly sharing your materials. In addition, material has been drawn from [Software Carpentry](http://software-carpentry.org), [Data Carpentry](http://datacarpentry.org/), and from R seminars given by numerous individuals at the USGS Center for Integrated Data Analytics and the USGS Wisconsin Water Science Center at the 2014-2015 R Lunch Bunch Data Crunch seminar series. We are grateful to all of these sources.

Each step of the workflow has a written component (blog post) describing the topic, a demonstration of example code, and hands-on exercises. The R code found in each blog post is also available as a stand-alone R script of the same name. The blog posts are intended to be used as a reference after the workshop. 

##Tentative Schedule

## Day 1

### [01 - Introduction (8:30 am - 10:00 am)](A_Introduction.html)

- Getting R and RStudio going
- Using packages
- Using functions
- Help!

#### Break (10:00 am - 10:15 am)

### [02 - Get (10:15 am - 12:00 pm)](B_Get.html)

- Working in the console
- Useful functions
- Data types and structures in R
- Reading data into R

#### Lunch (12:00 pm - 1:00 pm)

### [03 - Clean (1:00 pm - 2:45 pm)](C_Clean.html)

- `dplyr` 
- Subset
- Reshape
- Modify
- Pipes

#### Break (2:45 pm - 3:00 pm)

### [04 - Explore (3:00 pm - 4:30 pm)](D_Explore.html)

- Exploratory data analysis
- Summary Statistics
- Exploratory plots with base R

## Day 2

### [05 - Analyze: Base (8:30 am - 9:30 am)](E_Analyze.html)

- Base statistics

### [06 - Analyze: Using Packages (9:30 am - 10:45 am)](F_Analyze.html)

- Contributed Packages - dataRetrieval and EGRET

#### Break (10:45 am - 11:00 am)

### [07 - Visualize: Base (11:00 pm - 12:00 pm)](G_Visualize.html)

- Advanced plotting with base R

#### Lunch (12:00 pm - 1:00 pm)

### [08 - Visualize: ggplot2 (1:00 pm - 2:30 pm)](H_Visualize.html)

- Advanced plotting with ggplot2

#### Break (2:30 pm - 2:45 pm)

### [09 - Repeat (2:45 pm - 4:30 pm)](I_Repeat-Reproduce.html)

- Functions
- Programing with R
- Reproducible Research with RStudio (R Markdown)

## Day 3

### [10 - Practice (8:30 am - 10:30 am)]

- USGS R packages
- Work on projects (group/individual)
- Additional topics brought up during the workshop